### ISSUE TITLE
NullPointerException when running without any changes

### ISSUE THREAD

**Issue by TimoKramer** [Azure-Samples/resources-java-deploy-using-arm-template#8]
```null
java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at com.microsoft.azure.management.resources.samples.DeployUsingARMTemplate.main(DeployUsingARMTemplate.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:745)```

**Comment by amadav** [comment]
Environment variable for 'AZURE_AUTH_LOCATION' has to be set. The samples use file based authentication but you can use the ApplicationTokenCredentials API for the same.
